<?php

namespace common\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "video".
 *
 * @property string|null $id
 * @property string|null $title
 * @property string|null $description
 * @property string|null $path
 * @property int|null $has_thumbnail
 * @property int|null $status
 * @property string|null $tags
 * @property int|null $created_by
 * @property int|null $created_at
 *
 * @property User $createdBy
 */
class Video extends \yii\db\ActiveRecord
{
    /**
     * @var UploadedFile
     */
    public UploadedFile $video;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'video';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['description'], 'string'],
            [['has_thumbnail', 'status', 'created_by', 'created_at'], 'integer'],
            [['id'], 'string', 'max' => 16],
            [['title', 'path', 'tags'], 'string', 'max' => 512],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['created_by' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'description' => 'Description',
            'path' => 'Path',
            'has_thumbnail' => 'Has Thumbnail',
            'status' => 'Status',
            'tags' => 'Tags',
            'created_by' => 'Created By',
            'created_at' => 'Created At',
        ];
    }

    /**
     * Gets query for [[CreatedBy]].
     *
     * @return \yii\db\ActiveQuery|yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }


    protected function upload()
    {
        $path = Yii::getAlias("@frontend/web/storage/videos");
        if (!is_dir($path))
            mkdir($path);
        $name = "$this->id.mp4";
        $path .= "/$name";
        $this->video->saveAs($path);
        return $path;
    }


    public function save($runValidation = true, $attributeNames = null)
    {
        $isInsert = $this->isNewRecord;
        if ($isInsert) {
            $this->id = Yii::$app->security->generateRandomString(15);
            $this->path = $this->video->name;
        }

        $saved = parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub

        if (!$saved)
            return false;

        if($isInsert)
            $this->upload();

        return true;
    }

    /**
     * {@inheritdoc}
     * @return VideoQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new VideoQuery(get_called_class());
    }
}
